# This is a human-maintainable environment yaml file with minimal indications
# of versions. it is used for setting up the environment by humans
# and docker2repo.
# It will use the newest available and compatible software versions,
# which may not be desirable for 100% replication.
# Reproducibility may be easier when running the environment as a Docker image
name: living-research
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3
  - pandoc
  - pandoc-crossref
  - pip
  - jupyterlab
  #
  - pip:
    - jupyter-repo2docker
  - matplotlib
  - numpy
